--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.1.230.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 07/11/2025 09:55:39
-- Server version: 5.7.44
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE dbTestAurelius;

--
-- Drop table `FasiProduzione`
--
DROP TABLE IF EXISTS FasiProduzione;

--
-- Drop table `Fasi`
--
DROP TABLE IF EXISTS Fasi;

--
-- Drop table `Macchine`
--
DROP TABLE IF EXISTS Macchine;

--
-- Drop table `Componenti`
--
DROP TABLE IF EXISTS Componenti;

--
-- Drop table `PartiProduzione`
--
DROP TABLE IF EXISTS PartiProduzione;

--
-- Drop table `Parti`
--
DROP TABLE IF EXISTS Parti;

--
-- Drop table `ArticoliProduzione`
--
DROP TABLE IF EXISTS ArticoliProduzione;

--
-- Drop table `Articoli`
--
DROP TABLE IF EXISTS Articoli;

--
-- Drop table `Prodotti`
--
DROP TABLE IF EXISTS Prodotti;

--
-- Drop table `Ordini`
--
DROP TABLE IF EXISTS Ordini;

--
-- Drop table `Clienti`
--
DROP TABLE IF EXISTS Clienti;

--
-- Set default database
--
USE dbTestAurelius;

--
-- Create table `Clienti`
--
CREATE TABLE Clienti (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Nome varchar(50) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `Ordini`
--
CREATE TABLE Ordini (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Data datetime DEFAULT NULL,
  Scadenza datetime DEFAULT NULL,
  ID_Cliente int(11) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE Ordini
ADD CONSTRAINT FK_Ordini_Clienti_ID_Cliente FOREIGN KEY (ID_Cliente)
REFERENCES Clienti (ID);

--
-- Create table `Prodotti`
--
CREATE TABLE Prodotti (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Descrizione varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `Articoli`
--
CREATE TABLE Articoli (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Qta int(11) DEFAULT NULL,
  ID_Ordine int(11) NOT NULL,
  ID_Prodotto int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE Articoli
ADD CONSTRAINT FK_Articoli_Ordini_ID_Ordine FOREIGN KEY (ID_Ordine)
REFERENCES Ordini (ID);

--
-- Create foreign key
--
ALTER TABLE Articoli
ADD CONSTRAINT FK_Articoli_Prodotti_ID_Prodotto FOREIGN KEY (ID_Prodotto)
REFERENCES Prodotti (ID);

--
-- Create table `ArticoliProduzione`
--
CREATE TABLE ArticoliProduzione (
  ID int(11) NOT NULL AUTO_INCREMENT,
  ID_Articolo int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE ArticoliProduzione
ADD CONSTRAINT FK_ArticoliProduzione_Articoli_ID_Articolo FOREIGN KEY (ID_Articolo)
REFERENCES Articoli (ID);

--
-- Create table `Parti`
--
CREATE TABLE Parti (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Descrizione varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `PartiProduzione`
--
CREATE TABLE PartiProduzione (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Qta int(11) DEFAULT NULL,
  ID_Articolo int(11) NOT NULL,
  ID_parte int(11) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE PartiProduzione
ADD CONSTRAINT FK_PartiProduzione_ArticoliProduzione_ID_Articolo FOREIGN KEY (ID_Articolo)
REFERENCES ArticoliProduzione (ID);

--
-- Create foreign key
--
ALTER TABLE PartiProduzione
ADD CONSTRAINT FK_PartiProduzione_Parti_ID_parte FOREIGN KEY (ID_parte)
REFERENCES Parti (ID);

--
-- Create table `Componenti`
--
CREATE TABLE Componenti (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Qta int(11) DEFAULT NULL,
  ID_Prodotto int(11) DEFAULT NULL,
  ID_Parte int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE Componenti
ADD CONSTRAINT FK_Componenti_Parti_ID_Parte FOREIGN KEY (ID_Parte)
REFERENCES Parti (ID);

--
-- Create foreign key
--
ALTER TABLE Componenti
ADD CONSTRAINT FK_Componenti_Prodotti_ID_Prodotto FOREIGN KEY (ID_Prodotto)
REFERENCES Prodotti (ID);

--
-- Create table `Macchine`
--
CREATE TABLE Macchine (
  Id int(11) NOT NULL AUTO_INCREMENT,
  DEscrizione varchar(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `Fasi`
--
CREATE TABLE Fasi (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Descrizione varchar(50) DEFAULT NULL,
  PartProgram varchar(80) DEFAULT NULL,
  ID_Parte int(11) NOT NULL,
  Id_Macchina int(11) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE Fasi
ADD CONSTRAINT FK_Fasi_Macchine_Id_Macchina FOREIGN KEY (Id_Macchina)
REFERENCES Macchine (Id);

--
-- Create foreign key
--
ALTER TABLE Fasi
ADD CONSTRAINT FK_Fasi_Parti_ID_Parte FOREIGN KEY (ID_Parte)
REFERENCES Parti (ID);

--
-- Create table `FasiProduzione`
--
CREATE TABLE FasiProduzione (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Qta_Richiesta int(11) DEFAULT NULL,
  Qta_Eseguita int(11) DEFAULT NULL,
  ID_Parte int(11) NOT NULL,
  Id_fase int(11) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE FasiProduzione
ADD CONSTRAINT FK_FasiProduzione_Fasi_Id_fase FOREIGN KEY (Id_fase)
REFERENCES Fasi (Id);

--
-- Create foreign key
--
ALTER TABLE FasiProduzione
ADD CONSTRAINT FK_FasiProduzione_PartiProduzione_ID_Parte FOREIGN KEY (ID_Parte)
REFERENCES PartiProduzione (ID);

-- 
-- Dumping data for table Clienti
--
INSERT INTO Clienti(ID, Nome) VALUES
(1, 'Giuseppe Petronella');

-- 
-- Dumping data for table Prodotti
--
INSERT INTO Prodotti(ID, Descrizione) VALUES
(1, 'Armadio');

-- 
-- Dumping data for table Ordini
--
INSERT INTO Ordini(ID, Data, Scadenza, ID_Cliente) VALUES
(2, '2025-11-06 00:00:00', '2025-11-22 00:00:00', 1);

-- 
-- Dumping data for table Articoli
--
INSERT INTO Articoli(ID, Qta, ID_Ordine, ID_Prodotto) VALUES
(1, 1, 2, 1);

-- 
-- Dumping data for table ArticoliProduzione
--
INSERT INTO ArticoliProduzione(ID, ID_Articolo) VALUES
(1, 1);

-- 
-- Dumping data for table Parti
--
INSERT INTO Parti(ID, Descrizione) VALUES
(1, 'Anta sx');

-- 
-- Dumping data for table Macchine
--
INSERT INTO Macchine(Id, DEscrizione) VALUES
(1, 'Centro di lavoro 7410'),
(2, 'Bordatrice Auriga XL');

-- Table dbTestAurelius.PartiProduzione does not contain any data (it is empty)

-- 
-- Dumping data for table Fasi
--
INSERT INTO Fasi(Id, Descrizione, PartProgram, ID_Parte, Id_Macchina) VALUES
(1, 'Taglio anta sx', 'Anta sx.hop', 1, 1),
(2, 'Bordatura', 'Antasx.bor', 1, 2);

-- Table dbTestAurelius.FasiProduzione does not contain any data (it is empty)

-- 
-- Dumping data for table Componenti
--
INSERT INTO Componenti(ID, Qta, ID_Prodotto, ID_Parte) VALUES
(1, 1, 1, 1);

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;