--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 07/11/2025 15:33:04
-- Server version: 8.0.34
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE dbtestaurelius;

--
-- Drop table `fasiproduzione`
--
DROP TABLE IF EXISTS fasiproduzione;

--
-- Drop table `fasi`
--
DROP TABLE IF EXISTS fasi;

--
-- Drop table `macchine`
--
DROP TABLE IF EXISTS macchine;

--
-- Drop table `componenti`
--
DROP TABLE IF EXISTS componenti;

--
-- Drop table `partiproduzione`
--
DROP TABLE IF EXISTS partiproduzione;

--
-- Drop table `parti`
--
DROP TABLE IF EXISTS parti;

--
-- Drop table `articoliproduzione`
--
DROP TABLE IF EXISTS articoliproduzione;

--
-- Drop table `articoli`
--
DROP TABLE IF EXISTS articoli;

--
-- Drop table `prodotti`
--
DROP TABLE IF EXISTS prodotti;

--
-- Drop table `ordini`
--
DROP TABLE IF EXISTS ordini;

--
-- Drop table `clienti`
--
DROP TABLE IF EXISTS clienti;

--
-- Set default database
--
USE dbtestaurelius;

--
-- Create table `clienti`
--
CREATE TABLE clienti (
  ID int NOT NULL AUTO_INCREMENT,
  Nome varchar(50) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `ordini`
--
CREATE TABLE ordini (
  ID int NOT NULL AUTO_INCREMENT,
  Data datetime DEFAULT NULL,
  Scadenza datetime DEFAULT NULL,
  ID_Cliente int NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE ordini
ADD CONSTRAINT FK_Ordini_Clienti_ID_Cliente FOREIGN KEY (ID_Cliente)
REFERENCES clienti (ID);

--
-- Create table `prodotti`
--
CREATE TABLE prodotti (
  ID int NOT NULL AUTO_INCREMENT,
  Descrizione varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `articoli`
--
CREATE TABLE articoli (
  ID int NOT NULL AUTO_INCREMENT,
  Qta int DEFAULT NULL,
  ID_Ordine int NOT NULL,
  ID_Prodotto int DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE articoli
ADD CONSTRAINT FK_Articoli_Ordini_ID_Ordine FOREIGN KEY (ID_Ordine)
REFERENCES ordini (ID);

--
-- Create foreign key
--
ALTER TABLE articoli
ADD CONSTRAINT FK_Articoli_Prodotti_ID_Prodotto FOREIGN KEY (ID_Prodotto)
REFERENCES prodotti (ID);

--
-- Create table `articoliproduzione`
--
CREATE TABLE articoliproduzione (
  ID int NOT NULL AUTO_INCREMENT,
  ID_Articolo int DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE articoliproduzione
ADD CONSTRAINT FK_ArticoliProduzione_Articoli_ID_Articolo FOREIGN KEY (ID_Articolo)
REFERENCES articoli (ID);

--
-- Create table `parti`
--
CREATE TABLE parti (
  ID int NOT NULL AUTO_INCREMENT,
  Descrizione varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `partiproduzione`
--
CREATE TABLE partiproduzione (
  ID int NOT NULL AUTO_INCREMENT,
  Qta int DEFAULT NULL,
  ID_Articolo int NOT NULL,
  ID_parte int NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE partiproduzione
ADD CONSTRAINT FK_PartiProduzione_ArticoliProduzione_ID_Articolo FOREIGN KEY (ID_Articolo)
REFERENCES articoliproduzione (ID) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE partiproduzione
ADD CONSTRAINT FK_PartiProduzione_Parti_ID_parte FOREIGN KEY (ID_parte)
REFERENCES parti (ID);

--
-- Create table `componenti`
--
CREATE TABLE componenti (
  ID int NOT NULL AUTO_INCREMENT,
  Qta int DEFAULT NULL,
  ID_Prodotto int DEFAULT NULL,
  ID_Parte int DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE componenti
ADD CONSTRAINT FK_Componenti_Parti_ID_Parte FOREIGN KEY (ID_Parte)
REFERENCES parti (ID);

--
-- Create foreign key
--
ALTER TABLE componenti
ADD CONSTRAINT FK_Componenti_Prodotti_ID_Prodotto FOREIGN KEY (ID_Prodotto)
REFERENCES prodotti (ID);

--
-- Create table `macchine`
--
CREATE TABLE macchine (
  Id int NOT NULL AUTO_INCREMENT,
  DEscrizione varchar(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `fasi`
--
CREATE TABLE fasi (
  Id int NOT NULL AUTO_INCREMENT,
  Descrizione varchar(50) DEFAULT NULL,
  PartProgram varchar(80) DEFAULT NULL,
  ID_Parte int NOT NULL,
  Id_Macchina int NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE fasi
ADD CONSTRAINT FK_Fasi_Macchine_Id_Macchina FOREIGN KEY (Id_Macchina)
REFERENCES macchine (Id);

--
-- Create foreign key
--
ALTER TABLE fasi
ADD CONSTRAINT FK_Fasi_Parti_ID_Parte FOREIGN KEY (ID_Parte)
REFERENCES parti (ID);

--
-- Create table `fasiproduzione`
--
CREATE TABLE fasiproduzione (
  ID int NOT NULL AUTO_INCREMENT,
  Qta_Richiesta int DEFAULT NULL,
  Qta_Eseguita int DEFAULT NULL,
  ID_Parte int NOT NULL,
  Id_fase int NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE fasiproduzione
ADD CONSTRAINT FK_FasiProduzione_Fasi_Id_fase FOREIGN KEY (Id_fase)
REFERENCES fasi (Id);

--
-- Create foreign key
--
ALTER TABLE fasiproduzione
ADD CONSTRAINT FK_FasiProduzione_PartiProduzione_ID_Parte FOREIGN KEY (ID_Parte)
REFERENCES partiproduzione (ID) ON DELETE CASCADE;

-- 
-- Dumping data for table clienti
--
INSERT INTO clienti(ID, Nome) VALUES
(1, 'Giuseppe Petronella');

-- 
-- Dumping data for table prodotti
--
INSERT INTO prodotti(ID, Descrizione) VALUES
(1, 'Armadio');

-- 
-- Dumping data for table ordini
--
INSERT INTO ordini(ID, Data, Scadenza, ID_Cliente) VALUES
(2, '2025-11-06 00:00:00', '2025-11-22 00:00:00', 1);

-- 
-- Dumping data for table articoli
--
INSERT INTO articoli(ID, Qta, ID_Ordine, ID_Prodotto) VALUES
(1, 1, 2, 1);

-- 
-- Dumping data for table articoliproduzione
--
INSERT INTO articoliproduzione(ID, ID_Articolo) VALUES
(5, 1);

-- 
-- Dumping data for table parti
--
INSERT INTO parti(ID, Descrizione) VALUES
(1, 'Anta sx');

-- 
-- Dumping data for table macchine
--
INSERT INTO macchine(Id, DEscrizione) VALUES
(1, 'Centro di lavoro 7410'),
(2, 'Bordatrice Auriga XL');

-- 
-- Dumping data for table partiproduzione
--
INSERT INTO partiproduzione(ID, Qta, ID_Articolo, ID_parte) VALUES
(4, 1, 5, 1);

-- 
-- Dumping data for table fasi
--
INSERT INTO fasi(Id, Descrizione, PartProgram, ID_Parte, Id_Macchina) VALUES
(1, 'Taglio anta sx', 'Anta sx.hop', 1, 1),
(2, 'Bordatura', 'Antasx.bor', 1, 2);

-- 
-- Dumping data for table fasiproduzione
--
INSERT INTO fasiproduzione(ID, Qta_Richiesta, Qta_Eseguita, ID_Parte, Id_fase) VALUES
(7, 1, 1, 4, 1),
(8, 1, 1, 4, 2);

-- 
-- Dumping data for table componenti
--
INSERT INTO componenti(ID, Qta, ID_Prodotto, ID_Parte) VALUES
(1, 1, 1, 1);

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;